export const versionList = [
  { code: "cuv", lang: "cn", label: "和合本" },
  { code: "cunpss", lang: "cn", label: "和合本（新标点）" },
  { code: "rcuvss", lang: "cn", label: "和合本（修订版）" },
  { code: "cnvs", lang: "cn", label: "新译本" },
  { code: "ccb", lang: "cn", label: "当代译本" },
  { code: "kjv", lang: "en", label: "King James Version" },
  { code: "nkjv", lang: "en", label: "New King James Version" },
  { code: "esv", lang: "en", label: "English Standard Version" },
  { code: "niv", lang: "en", label: "New International Version" },
  { code: "nlt", lang: "en", label: "New Living Translation" },
  { code: "nasb", lang: "en", label: "New American Standard Bible" },
  { code: "csb", lang: "en", label: "Christian Standard Bible" },
];
export const chineseBookNames = [
  "创世纪",
  "出埃及记",
  "利未记",
  "民数记",
  "申命记",
  "约书亚记",
  "士师记",
  "路得记",
  "撒母耳记上",
  "撒母耳记下",
  "列王纪上",
  "列王纪下",
  "历代志上",
  "历代志下",
  "以斯拉记",
  "尼希米记",
  "以斯帖记",
  "约伯记",
  "诗篇",
  "箴言",
  "传道书",
  "雅歌",
  "以赛亚书",
  "耶利米书",
  "耶利米哀歌",
  "以西结书",
  "但以理书",
  "何西阿书",
  "约珥书",
  "阿摩司书",
  "俄巴底亚书",
  "约拿书",
  "弥迦书",
  "那鸿书",
  "哈巴谷书",
  "西番雅书",
  "哈该书",
  "撒迦利亚书",
  "玛拉基书",
  "马太福音",
  "马可福音",
  "路加福音",
  "约翰福音",
  "使徒行传",
  "罗马书",
  "哥林多前书",
  "哥林多后书",
  "加拉太书",
  "以弗所书",
  "腓立比书",
  "歌罗西书",
  "帖撒罗尼迦前书",
  "帖撒罗尼迦后书",
  "提摩太前书",
  "提摩太后书",
  "提多书",
  "腓利门书",
  "希伯来书",
  "雅各书",
  "彼得前书",
  "彼得后书",
  "约翰一书",
  "约翰二书",
  "约翰三书",
  "犹大书",
  "启示录",
];
export const englishBookNames = [
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Ruth",
  "1 Samuel",
  "2 Samuel",
  "1 Kings",
  "2 Kings",
  "1 Chronicles",
  "2 Chronicles",
  "Ezra",
  "Nehemiah",
  "Esther",
  "Job",
  "Psalms",
  "Proverbs",
  "Ecclesiastes",
  "Song of Songs",
  "Isaiah",
  "Jeremiah",
  "Lamentations",
  "Ezekiel",
  "Daniel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi",
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Romans",
  "1 Corinthians",
  "2 Corinthians",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "1 Thessalonians",
  "2 Thessalonians",
  "1 Timothy",
  "2 Timothy",
  "Titus",
  "Philemon",
  "Hebrews",
  "James",
  "1 Peter",
  "2 Peter",
  "1 John",
  "2 John",
  "3 John",
  "Jude",
  "Revelation",
];
export const chapterCounts = [
  50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 10, 42, 150,
  31, 12, 8, 66, 52, 5, 48, 12, 14, 3, 9, 1, 4, 7, 3, 3, 3, 2, 14, 4, 28, 16,
  24, 21, 28, 16, 16, 13, 6, 6, 4, 4, 5, 3, 6, 4, 3, 1, 13, 5, 5, 3, 5, 1, 1, 1,
  22,
];
export const lightThemeList = ["#cccccc", "#c2a17a"];
export const darkThemeList = ["#8b8b8b", "#494949"];
